I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1023, in script
    f "PUNY HUMANS! GIVE UP AND I MIGHT CONSIDER SPARING YOU (as a consideration of our shared rugged good looks and impeccable fashion sense :0)"
Exception: Sayer 'f' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1023, in script
    f "PUNY HUMANS! GIVE UP AND I MIGHT CONSIDER SPARING YOU (as a consideration of our shared rugged good looks and impeccable fashion sense :0)"
  File "C:\Users\singi\Documents\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\singi\Documents\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'f' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
AE Party 1.0
Fri Aug 28 00:52:20 2020
